### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by edwin721** [GitHelge/resimulate#12]
Hello,
Firstly, your application is amazing, I have been using it for 3 years and it worked very well! Very useful for on field intensive care training.

But since the new version 1.3 I cannot connect two device (trainer, trainee). They don't detect other device.
I reinstalled the previous version and it work well.
If you need I can give you more detais.

Thanks a lot for your work.
Edwin

**Comment by GitHelge** [comment]
Hey Edwin, im happy you find the application useful. I had/wanted to update the app due to a looming deadline for outdated apps but I was not able to test all parts in their entirety and assumed they would continue to work. :/ There seem to have been some unexpected breaking changes in the Nearby Communication service that is used for the connection. Currently, I am assuming its just because of some additional Permissions that are now needed for the connection to work. https://developers.google.com/nearby/connections/overview?hl=en

I cannot revert the update aswell because Google does not allow this. So the only way is forward. :D 

Im happy you were able to install the previous version. Probably by installing some APK or so directly, I assume. 
I will need time to get it into a fully working state again im afraid.

**Comment by GitHelge** [comment]
I will probably find some time tomorrow to make further investigations on the issues.

**Comment by GitHelge** [comment]
@edwin721 It would probably be helpful to know, on which version of Android you run your devices on?

**Comment by edwin721** [comment]
Hello,
Trainer use :
Android 13 TKQ 1.221114.001


Trainee use:
Android 13, I don't find the exact version. (Lenovo tab M10 plus 3rd
Generation)


Le ven. 29 déc. 2023, 13:22, Christian Bauer ***@***.***> a
écrit :

**Comment by GitHelge** [comment]
Thanks for the Info I pushed version 1.3.1 which should be available in a couple of hours. The issue was in fact based on necessary permission changes for newer versions of Android. I was now able to test the connections and solve the issue. 

Will be fixed in https://github.com/GitHelge/resimulate/pull/13

**Comment by edwin721** [comment]
I load the new version, it works just well. Thanks a lot.
